print("Content-Typesedwfdfdsfsdfsd: text/html\n")
print("Content-Typesedwfdfdsfsdfsd: text/html\n")
print("Content-Typesedwfdfdsfsdfsd: text/html\n")
print("Content-Typesedwfdfdsfsdfsd: text/html\n")
print("Content-Typesedwfdfdsfsdfsd: text/html\n")  
